### ISSUE TITLE
I can not pass cnvnator process. 

### ISSUE THREAD

**Issue by Yothin-H** [robinjugas/ProcaryaSV#1]
Hello, I am trying to find SV on bacterial genome. I tried use ProcaryaSV and I can not solve this problem from cnvnator. 
[B110-LEG3394_L3_cnvnator.log](https://github.com/user-attachments/files/17549426/B110-LEG3394_L3_cnvnator.log)

Thank you in advance

**Comment by robinjugas** [comment]
Hi,
it seems to be some bug in CNVnator and ROOT software. Try running without cnvNator firstly. Also, check if you have 
"root6 requires gcc 4.8" installed. 

https://root-forum.cern.ch/t/crash-with-cnvnator-and-root/24837/2
https://github.com/abyzovlab/CNVnator/issues/67

**Comment by diegovalenzuelam** [comment]
Hi! 

I've been trying to run ProcaryaSV but it keep failing at the mapping step with bwa. I'm getting the following error message: 

Activating conda environment: .snakemake/conda/e62e7906335affbf431ffe8abb9158a0_
Traceback (most recent call last):
  File "/home/usuario/ProcaryaSV/BKD/.snakemake/scripts/tmpnom35bef.bwa_mem2.py", line 22, in <module>
    index = path.splitext(snakemake.input.idx)[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 118, in splitext
TypeError: expected str, bytes or os.PathLike object, not Namedlist

any thoughts?

Thanks!

**Comment by robinjugas** [comment]
Hi, can you send me the log from that rule?
